spring.application.name=BiteNowAPI
server.port=8081

# mongodb configuration
spring.data.mongodb.uri=${MONGODB_URI}

# AWS s3 configuration
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.s3.bucketname=amzn-s3-bitenow

jwt.secret.key=${JWT_SECRET_KEY}

